# docker-compose.yml
version: '3.8'

services:
  # Serviço do Backend (API)
  backend:
    build:
      context: ./barberflow_api
    environment:
      # As variáveis de ambiente serão injetadas pelo Coolify
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    # A linha 'depends_on' foi removida daqui

  # Serviço do Frontend
  frontend:
    build:
      context: ./barberflow-frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
